* Signing Git Commits

I recently had a discussion with two fellow engineers about secure coding practices.
After the discussion I realized that I am neglecting one of the most important practices: signing my commits.

There are tons of articles on the internet explaining why and how. These are my notes on the subject that I decided to publish.

** Why bother?

Signing commits, allows you to track who made the commit and that the commit has not been tampered with.
More specifically, it allows you to verify that commit is signed using either a GPG key or an SSH key.

Does this protect you in the case your Github account get's compromised?
No, it does not as the attacker most likely will change the signing key.
Still, it verifies that the commit was not signed by your key.
If you are using GPG, where keys are public, it also allows others to verify that the commit was signed by you.

** Using GPG to sign commits
Let's see how we can use GPG to sign commits.
*** Extracting the GPG Key ID

First, we need to extract the key ID of the GPG key we want to use.

#+name: extract-key-id
#+begin_src shell
gpg --list-keys "iocanel@gmail.com" | grep -v pub | grep -v sub | grep -v uid | xargs
#+end_src

The sections below will use `$KEY_ID` to refer to the actual value.

*** Configure Git to Use Your GPG Key

Extract the key ID and use it to configure Git:

#+begin_src shell :var KEY_ID=extract-key-id
git config --global commit.gpgsign true
git config --global gpg.program gpg
git config --global gpg.format openpgp
git config --global user.signingkey $KEY_ID
#+end_src

*** Export GPG Public Key for GitHub
Export your public key in ASCII-armored format for GitHub:

#+name: public-key-block
#+begin_src shell :var KEY_ID=extract-key-id
gpg --armor --export $KEY_ID
#+end_src

*** Add GPG Key to GitHub
There are two ways of dealing with it:
- Manualy
- Using the Github API   

**** Add it manually to the Github settings page

Go to https://github.com/settings/keys and manually add it.

**** Use gh and the Github API

***** Enable api access to GPG

#+begin_src shell
gh auth refresh -h github.com -s admin:gpg_key
#+end_src

***** Add the Key using gh and the API


#+begin_src shell
gpg --armor --export iocanel@gmail.com > /tmp/publickey.asc
gh api --method POST -H "Accept: application/vnd.github+json" /user/gpg_keys -f armored_public_key="$(cat /tmp/publickey.asc)"
rm /tmp/publickey.asc
#+end_src

** Using SSH to sign commits
*** Generate a new SSH key

#+begin_src shell
git config commit.gpgsign true
git config gpg.format ssh
git config gpg.ssh.program ssh-keygen
git config user.signingkey /home/iocanel/.ssh/id_rsa
#+end_src

*** Add SSH Singing Key to GitHub

Again, there are two ways of dealing with it (as with GPG):
- Manualy
- Using the Github API   

**** Add it manually to the Github settings page

Go to https://github.com/settings/keys and manually add it.

**** Use gh and the Github API

***** Enable api access to SSH signing keys

#+begin_src shell
gh auth refresh -h github.com -s admin:ssh_signing_key 
#+end_src

***** Add the Key using gh and the API

#+begin_src shell
gh api -X POST -H "Accept: application/vnd.github+json" /user/ssh_signing_keys -f key="$(cat ~/.ssh/id_rsa.pub)"  -f title="My SSH signing key"
#+end_src
** GPG or SSH?
I like the idea of using GPG keys for signing commits, due to the fact that they are public and can be used to verify the commit.
SSH in some scenarios and some integration might be more convenient.

